version: '3'

services:
    flask_img_1:
        container_name: flask_con_1
        build: ./flask/1/
        expose:
            - 80
        hostname: dockerflask1
        networks:
            public_net:
                ipv4_address: 192.168.0.11
    flask_img_2:
        container_name: flask_con_2
        build: ./flask/2/
        expose:
            - 80
        hostname: dockerflask2
        networks:
            public_net:
                ipv4_address: 192.168.0.22
    haproxy_img:
        build: ./haproxy
        ports:
            - 80:80
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: 192.168.0.33
        environment:
            - APP_1_IP=192.168.0.11
            - APP_2_IP=192.168.0.22
            - APACHE_EXPOSED_PORT=80
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24